"""
Reusable mixins for SQLAlchemy models.

Provides common functionality through composable mixins:
- UUIDMixin: UUID primary key
- TimestampMixin: created_at, updated_at
- SoftDeleteMixin: deleted_at for soft deletion
- AuditMixin: created_by, updated_by
- VersionMixin: Optimistic locking version field
"""

from datetime import datetime, timezone
from typing import Optional
from uuid import UUID

from sqlalchemy import func
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy import DateTime, Integer
from sqlalchemy.dialects.postgresql import UUID as PG_UUID


class UUIDMixin:
    """
    Provides UUID primary key.
    
    Usage:
        class User(UUIDMixin, Base):
            __tablename__ = "users"
            id: Mapped[UUID] = mapped_column(PG_UUID(as_uuid=True), primary_key=True)
    """
    id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
        doc="Primary key - UUID v4 generated by database",
    )


class TimestampMixin:
    """
    Provides created_at and updated_at timestamps.
    
    - created_at: Set once on insert
    - updated_at: Updated on every modification
    """
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        doc="Timestamp when record was created",
    )
    
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        doc="Timestamp when record was last updated",
    )


class SoftDeleteMixin:
    """
    Provides soft deletion support.
    
    - deleted_at: NULL for active records, timestamp for deleted records
    - Use is_deleted property to check deletion status
    """
    deleted_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
        doc="Timestamp when record was soft-deleted (NULL = active)",
    )
    
    @property
    def is_deleted(self) -> bool:
        """Check if record is deleted."""
        return self.deleted_at is not None
    
    def soft_delete(self) -> None:
        """Mark record as deleted."""
        self.deleted_at = func.now()


class AuditMixin:
    """
    Provides audit trail fields.
    
    - created_by: User who created the record
    - updated_by: User who last modified the record
    """
    created_by: Mapped[Optional[UUID]] = mapped_column(
        PG_UUID(as_uuid=True),
        nullable=True,
        doc="ID of user who created this record",
    )
    
    updated_by: Mapped[Optional[UUID]] = mapped_column(
        PG_UUID(as_uuid=True),
        nullable=True,
        doc="ID of user who last updated this record",
    )


class VersionMixin:
    """
    Provides optimistic locking version field.
    
    - version: Incremented on each update
    - Prevents concurrent modification conflicts
    """
    version: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=1,
        doc="Version number for optimistic locking (increments on update)",
    )


class BaseModel(
    UUIDMixin,
    TimestampMixin,
    SoftDeleteMixin,
    AuditMixin,
    VersionMixin,
):
    """
    Convenience base class combining all mixins.
    
    Most models should inherit from this class directly:
    
        class User(BaseModel, Base):
            __tablename__ = "users"
            ...
    """
    pass