"""
FraudAlert model for suspicious transaction detection.

Represents a real-time fraud alert generated by rules or ML models.
"""

from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING, Optional
from uuid import UUID

from sqlalchemy import String, Numeric, DateTime, ForeignKey, Text, CheckConstraint, Index
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base
from app.models.mixins import UUIDMixin, TimestampMixin, SoftDeleteMixin, AuditMixin, VersionMixin
from app.models.fraud.enums import AlertSeverity, AlertStatus, DetectionMethod

if TYPE_CHECKING:
    from app.models.transaction.transaction import Transaction
    from app.models.fraud.fraud_case import FraudCase
    from app.models.fraud.fraud_rule import FraudRule
    from app.models.identity.user import User


class FraudAlert(Base, UUIDMixin, TimestampMixin, SoftDeleteMixin, AuditMixin, VersionMixin):
    """
    Fraud alert representing suspicious transaction detection.
    
    Generated by fraud detection rules or ML models when a transaction exhibits
    suspicious patterns. Alerts are the entry point for fraud investigation.
    
    Design Rationale:
    - Lightweight: Minimal fields for fast alert generation
    - Traceable: Links to transaction, rule, and ML prediction
    - Workflow-driven: Status field drives analyst workflow
    - Severity-based: Prioritization for alert queue
    
    Attributes:
        alert_number: Unique alert reference number (business key)
        transaction_id: FK to transaction that triggered alert
        severity: Alert severity level (low/medium/high/critical)
        status: Current alert status in investigation workflow
        risk_score: Calculated risk score (0-100)
        detection_method: How alert was generated
        triggered_rule_id: FK to rule that triggered alert (if rule-based)
        assigned_analyst_id: FK to assigned analyst
        generated_at: When alert was created
        acknowledged_at: When analyst acknowledged alert
        resolved_at: When alert was resolved
        false_positive: Whether alert was determined to be false positive
        resolution_summary: Summary of resolution
    """
    __tablename__ = "fraud_alerts"
    
    # Business Key
    alert_number: Mapped[str] = mapped_column(
        String(50),
        unique=True,
        nullable=False,
        index=True,
        doc="Unique alert reference number",
    )
    
    # Foreign Keys
    transaction_id: Mapped[UUID] = mapped_column(
        ForeignKey("transactions.id", name="fk_fraud_alerts_transaction_id"),
        nullable=False,
        index=True,
        doc="Transaction that triggered alert",
    )
    
    triggered_rule_id: Mapped[Optional[UUID]] = mapped_column(
        ForeignKey("fraud_rules.id", name="fk_fraud_alerts_triggered_rule_id"),
        nullable=True,
        index=True,
        doc="Rule that triggered alert (if rule-based)",
    )
    
    assigned_analyst_id: Mapped[Optional[UUID]] = mapped_column(
        ForeignKey("users.id", name="fk_fraud_alerts_assigned_analyst_id"),
        nullable=True,
        index=True,
        doc="Analyst assigned to investigate",
    )
    
    # Classification
    severity: Mapped[AlertSeverity] = mapped_column(
        nullable=False,
        index=True,
        doc="Alert severity level",
    )
    
    status: Mapped[AlertStatus] = mapped_column(
        nullable=False,
        default=AlertStatus.NEW,
        index=True,
        doc="Current alert status",
    )
    
    detection_method: Mapped[Optional[DetectionMethod]] = mapped_column(
        nullable=True,
        doc="How alert was detected",
    )
    
    # Scoring
    risk_score: Mapped[Optional[float]] = mapped_column(
        Numeric(5, 2),
        nullable=True,
        doc="Calculated risk score (0-100)",
    )
    
    # Timestamps
    generated_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        index=True,
        doc="When alert was generated",
    )
    
    acknowledged_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        doc="When analyst acknowledged alert",
    )
    
    resolved_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        doc="When alert was resolved",
    )
    
    # Outcome
    false_positive: Mapped[Optional[bool]] = mapped_column(
        nullable=True,
        doc="Whether alert was false positive",
    )
    
    resolution_summary: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        doc="Summary of alert resolution",
    )
    
    # Relationships
    transaction: Mapped["Transaction"] = relationship(
        "Transaction",
        lazy="selectin",
        foreign_keys=[transaction_id],
    )
    
    rule: Mapped[Optional["FraudRule"]] = relationship(
        "FraudRule",
        back_populates="alerts",
        lazy="selectin",
    )
    
    assigned_analyst: Mapped[Optional["User"]] = relationship(
        "User",
        lazy="selectin",
        foreign_keys=[assigned_analyst_id],
    )
    
    case: Mapped[Optional["FraudCase"]] = relationship(
        "FraudCase",
        back_populates="alert",
        lazy="selectin",
        uselist=False,
    )
    
    # Composite Indexes
    __table_args__ = (
        Index("ix_fraud_alerts_status_severity", "status", "severity"),
        Index("ix_fraud_alerts_analyst_status", "assigned_analyst_id", "status"),
        Index("ix_fraud_alerts_transaction_generated", "transaction_id", "generated_at"),
        CheckConstraint(
            "risk_score IS NULL OR (risk_score >= 0 AND risk_score <= 100)",
            name="ck_fraud_alerts_risk_score_range",
        ),
    )
    
    def __repr__(self) -> str:
        return f"<FraudAlert {self.alert_number} status={self.status}>"