"""
FraudAlert model for suspicious transaction detection.

Represents a real-time fraud alert generated by rules or ML models.
"""

from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING, Optional
from uuid import UUID

from sqlalchemy import String, Numeric, DateTime, ForeignKey, Text, CheckConstraint, Index
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base
from app.models.mixins import UUIDMixin, TimestampMixin, SoftDeleteMixin, AuditMixin, VersionMixin
from app.models.fraud.enums import AlertSeverity, AlertStatus, DetectionMethod
from app.models.fraud.fraud_case import FraudCase

if TYPE_CHECKING:
    from app.models.transaction.transaction import Transaction
    from app.models.fraud.fraud_rule import FraudRule
    from app.models.identity.user import User
    from app.models.transaction.merchant import Merchant


class FraudAlert(Base, UUIDMixin, TimestampMixin, SoftDeleteMixin, AuditMixin, VersionMixin):
    __tablename__ = "fraud_alerts"

    # Business Key
    alert_number: Mapped[str] = mapped_column(
        String(50),
        unique=True,
        nullable=False,
        index=True,
        doc="Unique alert reference number",
    )

    # Details
    title: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        doc="Alert title",
    )

    description: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        doc="Alert description",
    )

    # Foreign Keys
    transaction_id: Mapped[UUID] = mapped_column(
        ForeignKey("transactions.id", name="fk_fraud_alerts_transaction_id"),
        nullable=False,
        index=True,
        doc="Transaction that triggered alert",
    )

    case_id: Mapped[Optional[UUID]] = mapped_column(
        nullable=True,
        index=True,
        doc="Associated fraud case",
    )

    merchant_id: Mapped[Optional[UUID]] = mapped_column(
        ForeignKey("merchants.id", name="fk_fraud_alerts_merchant_id"),
        nullable=True,
        index=True,
        doc="Related merchant",
    )

    triggered_rule_id: Mapped[Optional[UUID]] = mapped_column(
        ForeignKey("fraud_rules.id", name="fk_fraud_alerts_triggered_rule_id"),
        nullable=True,
        index=True,
        doc="Rule that triggered alert (if rule-based)",
    )

    assigned_analyst_id: Mapped[Optional[UUID]] = mapped_column(
        ForeignKey("users.id", name="fk_fraud_alerts_assigned_analyst_id"),
        nullable=True,
        index=True,
        doc="Analyst assigned to investigate",
    )

    creator_id: Mapped[Optional[UUID]] = mapped_column(
        ForeignKey("users.id", name="fk_fraud_alerts_creator_id"),
        nullable=True,
        index=True,
        doc="User who created the alert",
    )

    resolver_id: Mapped[Optional[UUID]] = mapped_column(
        ForeignKey("users.id", name="fk_fraud_alerts_resolver_id"),
        nullable=True,
        index=True,
        doc="User who resolved the alert",
    )

    # Classification
    severity: Mapped[AlertSeverity] = mapped_column(
        nullable=False,
        index=True,
        doc="Alert severity level",
    )

    status: Mapped[AlertStatus] = mapped_column(
        nullable=False,
        default=AlertStatus.NEW,
        index=True,
        doc="Current alert status",
    )

    detection_method: Mapped[Optional[DetectionMethod]] = mapped_column(
        nullable=True,
        doc="How alert was detected",
    )

    # Scoring
    risk_score: Mapped[Optional[float]] = mapped_column(
        Numeric(5, 2),
        nullable=True,
        doc="Calculated risk score (0-100)",
    )

    # Timestamps
    generated_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        index=True,
        doc="When alert was generated",
    )

    acknowledged_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        index=True,
        doc="When analyst acknowledged alert",
    )

    resolved_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        index=True,
        doc="When alert was resolved",
    )

    # Outcome
    false_positive: Mapped[Optional[bool]] = mapped_column(
        nullable=True,
        doc="Whether alert was false positive",
    )

    resolution_summary: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        doc="Summary of alert resolution",
    )

    # Relationships
    transaction: Mapped["Transaction"] = relationship(
        "Transaction",
        lazy="selectin",
        foreign_keys=[transaction_id],
    )

    case: Mapped[Optional[FraudCase]] = relationship(
        FraudCase,
        lazy="selectin",
        uselist=False,
    )

    merchant: Mapped[Optional["Merchant"]] = relationship(
        "Merchant",
        lazy="selectin",
    )

    rule: Mapped[Optional["FraudRule"]] = relationship(
        "FraudRule",
        back_populates="alerts",
        lazy="selectin",
    )

    assigned_analyst: Mapped[Optional["User"]] = relationship(
        "User",
        lazy="selectin",
        foreign_keys=[assigned_analyst_id],
    )

    creator: Mapped[Optional["User"]] = relationship(
        "User",
        lazy="selectin",
        foreign_keys=[creator_id],
    )

    resolver: Mapped[Optional["User"]] = relationship(
        "User",
        lazy="selectin",
        foreign_keys=[resolver_id],
    )

    # Composite Indexes
    __table_args__ = (
        Index("ix_fraud_alerts_status_severity", "status", "severity"),
        Index("ix_fraud_alerts_analyst_status", "assigned_analyst_id", "status"),
        Index("ix_fraud_alerts_transaction_generated", "transaction_id", "generated_at"),
        Index("ix_fraud_alerts_case", "case_id"),
        Index("ix_fraud_alerts_merchant", "merchant_id"),
        CheckConstraint(
            "risk_score IS NULL OR (risk_score >= 0 AND risk_score <= 100)",
            name="ck_fraud_alerts_risk_score_range",
        ),
    )

    def __repr__(self) -> str:
        return f"<FraudAlert {self.alert_number} status={self.status}>"
